#ifndef TRAP_H
#define TRAP_H

void trap_init();

typedef enum trap
{
	TRAP_DIVIDE_BY_ZERO = 0,
	TRAP_DEBUG = 1,
	TRAP_NMI = 2,
	TRAP_BREAKPOINT = 3,
	TRAP_OVERFLOW = 4,
	TRAP_BOUND_RANGE_EXCEEDED = 5,
	TRAP_INVALID_OPCODE = 6,
	TRAP_DEVICE_NOT_AVAILABLE = 7,
	TRAP_DOUBLE_FAULT = 8,
	TRAP_COPROCESSOR_SEG_OVERRUN = 9,
	TRAP_INVALID_TSS = 10,
	TRAP_SEGMENT_NOT_PRESENT = 11,
	TRAP_STACK_SEG_FAULT = 12,
	TRAP_GPF = 13,
	TRAP_PAGE_FAULT = 14,
	TRAP_FLOAT_X87 = 16,
	TRAP_ALIGN = 17,
	TRAP_MACHINE = 18,
	TRAP_FLOAT_SIMD = 19,
	TRAP_SECURITY = 30,
}
trap_t;

#endif